version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dpp
      POSTGRES_PASSWORD: dpp
      POSTGRES_DB: dpp
    ports:
      - "5432:5432"
    volumes:
      - dpp-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dpp"]
      interval: 5s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - dpp-minio:/data

  createbuckets:
    image: minio/mc:RELEASE.2024-07-26T19-55-10Z
    depends_on:
      - minio
    entrypoint: >-
      /bin/sh -c "
      mc alias set local http://minio:9000 minio minio123 &&
      mc mb -p local/dpp-evidence || true &&
      mc anonymous set download local/dpp-public || true &&
      mc mb -p local/dpp-public || true
      "

  passport-api:
    build:
      context: ./services/passport-api
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://dpp:dpp@postgres:5432/dpp?schema=public
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://minio:9000
      S3_REGION: eu-central-1
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio123
      S3_BUCKET_EVIDENCE: dpp-evidence
      PUBLIC_BUCKET: dpp-public
      ID_RESOLVER_BASE_URL: http://id-resolver:8082
      EPCIS_API_BASE_URL: http://epcis-api:8083
      PORT: 8081
      JWT_SECRET: dev-secret
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      createbuckets:
        condition: service_completed_successfully
    ports:
      - "8081:8081"

  id-resolver:
    build:
      context: ./services/id-resolver
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PORT: 8082
      PUBLIC_SITE_BASE_URL: http://public-site:5173
    depends_on:
      - passport-api
    ports:
      - "8082:8082"

  epcis-api:
    build:
      context: ./services/epcis-api
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PORT: 8083
      DATABASE_URL: postgresql://dpp:dpp@postgres:5432/dpp?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8083:8083"

  public-site:
    build:
      context: ./apps/public-site
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      VITE_PASSPORT_API_BASE_URL: http://passport-api:8081
      PORT: 5173
    depends_on:
      - passport-api
    ports:
      - "5173:5173"

volumes:
  dpp-postgres:
  dpp-minio: